### ISSUE TITLE
How I can use a full setup for specific PHP version

### ISSUE THREAD

**Issue by jfreites** [romeOz/docker-nginx-php#1]
Hi, 

The container use PHP based on this image romeoz/docker-phpfpm:5.4, and I can see that I can use a Full version with Mongo and Memcached extension already installed.

How I can get it in this image? Thank you!

**Comment by romeOz** [comment]
Hi.
Look in README - ["Adding PHP-extension"](https://github.com/romeOz/docker-nginx-php#adding-php-extension). Second approach is most best, namely:

Create your container on based the current. Сontents `Dockerfile`:

```
FROM romeoz/docker-nginx-php:5.4

RUN apt-get update \
    && apt-get install -y php-mongo php-memcached \
    && rm -rf /var/lib/apt/lists/* 

WORKDIR /var/www/app/

EXPOSE 80 443

CMD ["/usr/bin/supervisord"]
```

Next step,

```
docker build -t your-image-php-5.4 .
docker run --name app -d -p 8080:80 your-image-php-5.4
```

> See installed php-extension: docker exec -it app php -m


Good luck :wink:
