### ISSUE TITLE
5.3 tag is broken. Reality: php version is 5.6 

### ISSUE THREAD

**Issue by claudiobastos** [romeOz/docker-nginx-php#3]
Hi,

just fyi , your image with 5.3 tag is broken.
It's PHP inside is 5.6 (probably because FROM ubuntu:precise )...

**Comment by romeOz** [comment]
Verified. The images with PHP 5.3 runs success.
`docker run --name app -d -p 8080:80 romeoz/docker-nginx-php:5.3` or `docker run --name app -d romeoz/docker-phpfpm:5.3`

Verified: `docker exec -it app php -v`
Profit:
![2018-05-01 19-18-52](https://user-images.githubusercontent.com/3135712/39482433-ae260662-4d77-11e8-9942-b175d78fe823.png)

In Ubuntu 12.04 (Precise) PHP 5.3  is out of the box ([official repository of Ubuntu](https://launchpad.net/ubuntu/precise/+package/php5-fpm))
